AWSTemplateFormatVersion: 2010-09-09

Description: Storage resources for Kusama validators

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: Kusama validator chain state and keystore volume parameters
          Parameters:
            - EbsKusamaValidatorKeyStoreVolumeEncryptionKeyArn
            - EbsKusamaValidatorChainStateVolumeEncryptionKeyArn
            - EbsKusamaValidatorChainStateVolumeSize
            - EbsKusamaValidatorVolumesAz

    ParameterLabels:
      EbsKusamaValidatorKeyStoreVolumeEncryptionKeyArn:
        default: Validator keystore volume encryption key ARN
      EbsKusamaValidatorChainStateVolumeEncryptionKeyArn:
        default: Validator root and chain state volume encryption key ARN
      EbsKusamaValidatorChainStateVolumeSize:
        default: Size of chain state volume
      EbsKusamaValidatorVolumesAz:
        default: Volumes AZ

Parameters:
  EbsKusamaValidatorKeyStoreVolumeEncryptionKeyArn:
    Type: String
    Default: arn:aws:iam::!! AWS::Account !!:key/!! Key ID !!
    MinLength: 1
    MaxLength: 96
    Description: ARN of KMS key for keystore volume encryption

  EbsKusamaValidatorChainStateVolumeEncryptionKeyArn:
    Type: String
    Default: arn:aws:iam::!! AWS::Account !!:key/!! Key ID !!
    MinLength: 1
    MaxLength: 96
    Description: ARN of KMS key for root an chain state volume encryption

  EbsKusamaValidatorChainStateVolumeSize:
    Type: Number
    Default: 400
    MinValue: 1
    MaxValue: 2000
    Description: Size of Kusama validator chain state volume

  EbsKusamaValidatorVolumesAz:
    Type: String
    Default: us-east-2a
    MinLength: 1
    MaxLength: 64
    Description: Availibility Zone of Kusama volumes

Resources:
  EbsKusamaValidatorKeyStoreVolume:
    Type: AWS::EC2::Volume
    # DeletionPolicy: Snapshot
    Properties: 
      Size: 1
      Encrypted: true
      KmsKeyId: !Ref EbsKusamaValidatorKeyStoreVolumeEncryptionKeyArn
      AvailabilityZone: !Ref EbsKusamaValidatorVolumesAz
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: kusama-validator-keystore

Outputs:
  EbsKusamaValidatorKeyStoreVolumeId:
    Description: Volume ID of validator keystore volume
    Value: !GetAtt EbsKusamaValidatorKeyStoreVolume.VolumeId
    Export:
      Name: !Sub ${AWS::StackName}-${AWS::Region}-validator-keystore-volume-id