AWSTemplateFormatVersion: 2010-09-09

Description: ECS Kusama validator task definition

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: ECS Task Definition parameters
          Parameters:
            - EcsKusamaValidatorTaskDefinitionName
            - EcsKusamaValidatorTelemetryName
            - EcsKusamaValidatorNodeKeyPath
            - EcsKusamaValidatorTaskExecutionRole

    ParameterLabels:
      EcsKusamaValidatorTaskDefinitionName:
        default: Task definition name
      EcsKusamaValidatorTelemetryName:
        default: Validator name in W3F telemetry
      EcsKusamaValidatorNodeKeyPath:
        default: Node key file in (suggestion - keep in key store)
      EcsKusamaValidatorTaskExecutionRole:
        default: Validator task definition role ARN

Parameters:
  EcsKusamaValidatorTaskDefinitionName:
    Type: String
    Default: kusama-validator-task
    Description: Name of Kusama validator task definition

  EcsKusamaValidatorTelemetryName:
    Type: String
    Default: my-very-own-kusama-validator
    Description: Name of Kusama validator as it will appear in W3F telemetry (needs to be unique globally)

  EcsKusamaValidatorNodeKeyPath:
    Type: String
    Default: node.key
    Description: Path to node key file in the key store (suggestion - create node.key file in the root of the secrets volume)

  EcsKusamaValidatorTaskExecutionRole:
    Type: String
    Description: ARN of Kusama validator IAM execution role

Resources:
  EcsKusamaValidatorTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref EcsKusamaValidatorTaskDefinitionName
      ExecutionRoleArn: !Ref EcsKusamaValidatorTaskExecutionRole
      RequiresCompatibilities:
      - EC2
      Volumes:
        - Name: chainstate
          Host:
            SourcePath: /kusama/chainstate
        - Name: secrets
          Host:
            SourcePath: /kusama/secrets
      ContainerDefinitions:
        - Name: !Sub ${EcsKusamaValidatorTaskDefinitionName}-container
          Image: parity/polkadot:latest
          Command:
            - "--name"
            - !Sub "${EcsKusamaValidatorTelemetryName}"
            - "--telemetry-url"
            - "wss://telemetry-backend.w3f.community/submit 1"
            - "--prometheus-external"
            - "--prometheus-port"
            - "9615"
            - "--port"
            - "30333"
            - "--base-path"
            - "/polkadot/chainstate"
            - "--keystore-path"
            - "/polkadot/secrets"
            - "--node-key-file"
            - !Sub "/polkadot/secrets/${EcsKusamaValidatorNodeKeyPath}"
            - "--chain"
            - "kusama"
            - "--validator"
          WorkingDirectory: /polkadot
          Memory: 14000
          PortMappings:
            - ContainerPort: 30333
              HostPort: 30333
              Protocol: tcp
            - ContainerPort: 9615
              HostPort: 9615
              Protocol: tcp
          Essential: true
          MountPoints:
            - SourceVolume: chainstate
              ContainerPath: /polkadot/chainstate
              ReadOnly: false
            - SourceVolume: secrets
              ContainerPath: /polkadot/secrets
              ReadOnly: false
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Sub /ecs/${EcsKusamaValidatorTaskDefinitionName}
                awslogs-region: !Sub ${AWS::Region}
                awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Ref EcsKusamaValidatorTaskDefinitionName

  EcsKusamaValidatorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${EcsKusamaValidatorTaskDefinitionName}
      RetentionInDays: 60