AWSTemplateFormatVersion: 2010-09-09

Description: Identity Access Manager resources

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: EC2 instance role parameters
          Parameters:
            - Ec2KusamaNodeRoleName
        - Label:
            default: ECS task role parameters
          Parameters:
            - EcsKusamaNodeTaskExecutionRoleName

    ParameterLabels:
      Ec2KusamaNodeRoleName:
        default: IAM role name for validator EC2 instance
      EcsKusamaNodeTaskExecutionRoleName:
        default: IAM role name for validator ECS task

Parameters:
  Ec2KusamaNodeRoleName:
    Type: String
    Default: ec2KusamaNodeRole
    MinLength: 1
    MaxLength: 64
    Description: Name of IAM role for validator EC2 instance

  EcsKusamaNodeTaskExecutionRoleName:
    Type: String
    Default: ecsKusamaNodeTaskExecutionRole
    MinLength: 1
    MaxLength: 64
    Description: Name of IAM role for validator ECS task

Resources:
  Ec2KusamaNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref Ec2KusamaNodeRoleName
      Description: Allows validator instance run ECS tasks and use SSM
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
      - Key: Name
        Value: !Ref Ec2KusamaNodeRoleName

  Ec2KusamaNodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Ec2KusamaNodeRole

  EcsKusamaNodeTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EcsKusamaNodeTaskExecutionRoleName
      Description: Allows validator task run on ECS clusters
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
      - Key: Name
        Value: !Ref EcsKusamaNodeTaskExecutionRoleName

Outputs:
  Ec2KusamaNodeRoleArn:
    Description: ARN of Kusama node role
    Value: !GetAtt Ec2KusamaNodeRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${AWS::Region}-ec2-kusama-node-role-arn

  Ec2KusamaNodeInstanceProfileArn:
    Description: ARN of Kusama node instance profile
    Value: !GetAtt Ec2KusamaNodeInstanceProfile.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${AWS::Region}-ec2-kusama-node-inst-prof-arn

  EcsKusamaTaskExecutionRoleArn:
    Description: ARN of Kusama task execution role
    Value: !GetAtt EcsKusamaNodeTaskExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-${AWS::Region}-ecs-kusama-task-exec-role-arn