AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation stack piecing all the components together

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      # IAM parameter set
        - Label:
            default: EC2 instance role parameters (IAM)
          Parameters:
            - IamEc2KusamaNodeRoleName
        - Label:
            default: ECS task role parameters (IAM)
          Parameters:
            - IamEcsKusamaNodeTaskExecutionRoleName
      # KMS parameter set
        - Label:
            default: KMS key parameters (Security)
          Parameters:
            - KmsEbsVolumeEncryptionKeyAliasName
            - KmsEbsSecretsEncryptionKeyAliasName
            - KmsSessionManagerEncryptionKeyAliasName
            - KmsEbsVolumeEncryptionKeyDeleteWindow
      # VPC parameter set
        - Label:
            default: VPC parameters (Network)
          Parameters:
            - KusamaVpcName
            - KusamaVpcCidr
            - KusamaVpcOwner
        - Label:
            default: Security Group parameters (Network)
          Parameters:
            - KusamaValidatorP2pPort
            - KusamaValidatorPrometheusPort
      # EBS parameter set
        - Label:
            default: Kusama validator chain state and keystore volume parameters (Storage)
          Parameters:
            - StorageEbsKusamaValidatorChainStateVolumeSize
            - StorageEbsKusamaValidatorChainStateVolumeIops
            - StorageEbsKusamaValidatorChainStateVolumeThroughput
            - StorageEbsKusamaValidatorVolumesAz

    ParameterLabels:
    # IAM parameter set
      IamEc2KusamaNodeRoleName:
        default: IAM role name for validator EC2 instance
      IamEcsKusamaNodeTaskExecutionRoleName:
        default: IAM role name for validator ECS task
    # KMS parameter set
      KmsEbsVolumeEncryptionKeyAliasName:
        default: EBS volumes key alias
      KmsEbsSecretsEncryptionKeyAliasName:
        default: EBS secrets volume key alias
      KmsSessionManagerEncryptionKeyAliasName:
        default: Session Manager sessions key alias
      KmsEbsVolumeEncryptionKeyDeleteWindow:
        default: Key deletion window in days
    # VPC parameter set
      KusamaVpcName:
        default: VPC name
      KusamaVpcCidr:
        default: VPC CIDR block
      KusamaVpcOwner:
        default: Name of cluster owner
      KusamaValidatorP2pPort:
        default: Validator p2p port
      KusamaValidatorPrometheusPort:
        default: Validator Prometheus port
    # EBS parameter set
      StorageEbsKusamaValidatorChainStateVolumeSize:
        default: Size of chain state volume
      StorageEbsKusamaValidatorChainStateVolumeIops:
        default: Number of chain state volume IOPS (I/O operations per second)
      StorageEbsKusamaValidatorChainStateVolumeThroughput:
        default: Throughput of chain state volume
      StorageEbsKusamaValidatorVolumesAz:
        default: Volumes AZ

Parameters:
  # IAM parameter set
  IamEc2KusamaNodeRoleName:
    Type: String
    Default: ec2KusamaNodeRole
    MinLength: 1
    MaxLength: 64
    Description: Name of IAM role for validator EC2 instance

  IamEcsKusamaNodeTaskExecutionRoleName:
    Type: String
    Default: ecsKusamaNodeTaskExecutionRole
    MinLength: 1
    MaxLength: 64
    Description: Name of IAM role for validator ECS task

  # KMS parameter set
  KmsEbsVolumeEncryptionKeyAliasName:
    Type: String
    Default: kusama/volumes/ebs
    MinLength: 1
    MaxLength: 64
    Description: Alias for EBS volume encryption key

  KmsEbsSecretsEncryptionKeyAliasName:
    Type: String
    Default: kusama/secrets/ebs
    MinLength: 1
    MaxLength: 64
    Description: Alias for secrets EBS volume encryption key

  KmsSessionManagerEncryptionKeyAliasName:
    Type: String
    Default: kusama/sessions/sessionmanager
    MinLength: 1
    MaxLength: 64
    Description: Alias for Session Manager session encryption key

  KmsEbsVolumeEncryptionKeyDeleteWindow:
    Type: Number
    Default: 7
    MinValue: 7
    MaxValue: 30
    Description: How many days are needed before permanently deleting the key, [7-30]

  # VPC parameter set
  KusamaVpcName:
    Type: String
    Default: kusama-validator-vpc
    MinLength: 1
    MaxLength: 32
    Description: Name of VPC

  KusamaVpcCidr:
    Type: String
    Default: 10.0.0.0/26
    MinLength: 9
    MaxLength: 18
    Description: Address range of VPC

  KusamaVpcOwner:
    Type: String
    Default: me
    MinLength: 1
    MaxLength: 64
    Description: Owner (the IAM user you are operating as)

  KusamaValidatorP2pPort:
    Type: Number
    Default: 30333
    MinValue: 1025
    MaxValue: 65535
    Description: Port number for inter-node communication

  KusamaValidatorPrometheusPort:
    Type: Number
    Default: 9090
    MinValue: 1025
    MaxValue: 65535
    Description: Port number for Prometheus metrics

  # EBS parameter set
  StorageEbsKusamaValidatorChainStateVolumeSize:
    Type: Number
    Default: 400
    MinValue: 1
    MaxValue: 2000
    Description: Size of Kusama validator chain state volume

  StorageEbsKusamaValidatorChainStateVolumeIops:
    Type: Number
    Default: 6000
    MinValue: 3000
    MaxValue: 16000
    Description: IOPS of Kusama validator chain state volume [3000;16000]

  StorageEbsKusamaValidatorChainStateVolumeThroughput:
    Type: Number
    Default: 500
    MinValue: 125
    MaxValue: 1000
    Description: Throughput of Kusama validator chain state volume [125;1000]

  StorageEbsKusamaValidatorVolumesAz:
    Type: String
    Default: us-east-2a
    MinLength: 1
    MaxLength: 64
    Description: Availibility Zone of Kusama volumes

Resources:
  KusamaValidatorIamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cfn.kusama.orlowski.io/kusama/iam.yml
      Parameters:
        Ec2KusamaNodeRoleName: !Ref IamEc2KusamaNodeRoleName
        EcsKusamaNodeTaskExecutionRoleName: !Ref IamEcsKusamaNodeTaskExecutionRoleName

  KusamaValidatorKmsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cfn.kusama.orlowski.io/kusama/kms.yml
      Parameters:
        KusamaKmsEncryptionKeyUserRoleArn:
          Fn::GetAtt:
          - KusamaValidatorIamStack
          - Outputs.Ec2KusamaNodeRoleArn
        KusamaKmsEncryptionKeyAdminArn: !Sub arn:aws:iam::${AWS::AccountId}:user/${KusamaVpcOwner}
        EbsVolumeEncryptionKeyAliasName: !Ref KmsEbsVolumeEncryptionKeyAliasName
        EbsSecretsEncryptionKeyAliasName: !Ref KmsEbsSecretsEncryptionKeyAliasName
        SessionManagerEncryptionKeyAliasName: !Ref KmsSessionManagerEncryptionKeyAliasName
        EbsVolumeEncryptionKeyDeleteWindow: !Ref KmsEbsVolumeEncryptionKeyDeleteWindow

  KusamaValidatorVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cfn.kusama.orlowski.io/kusama/vpc.yml
      Parameters:
        VpcName: !Ref KusamaVpcName
        VpcCidr: !Ref KusamaVpcCidr
        VpcOwner: !Ref KusamaVpcOwner
        ValidatorP2pPort: !Ref KusamaValidatorP2pPort
        ValidatorPrometheusPort: !Ref KusamaValidatorPrometheusPort

  KusamaValidatorEbsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/cfn.kusama.orlowski.io/kusama/ebs.yml
      Parameters:
        EbsKusamaValidatorKeyStoreVolumeEncryptionKeyArn:
          Fn::GetAtt:
          - KusamaValidatorKmsStack
          - Outputs.EbsVolumeEncryptionKeyArn
        EbsKusamaValidatorChainStateVolumeEncryptionKeyArn:
          Fn::GetAtt:
          - KusamaValidatorKmsStack
          - Outputs.EbsSecretsEncryptionKeyArn
        EbsKusamaValidatorChainStateVolumeSize: !Ref StorageEbsKusamaValidatorChainStateVolumeSize
        EbsKusamaValidatorChainStateVolumeIops: !Ref StorageEbsKusamaValidatorChainStateVolumeIops
        EbsKusamaValidatorChainStateVolumeThroughput: !Ref StorageEbsKusamaValidatorChainStateVolumeThroughput
        # This should be obtained as output from VPC template
        EbsKusamaValidatorVolumesAz: !Ref StorageEbsKusamaValidatorVolumesAz